import Database from "../database/database";
import { Request, Response } from "express";

class SearchController {
    private db: Database;

    constructor() {
        this.db = new Database();
    }

    public getSearchData = async (req: Request, res: Response) => {
        try {
            const sql: string = `SELECT m.*, GROUP_CONCAT(mg.genre_name) AS genres
                                    FROM movie m
                                    LEFT JOIN movie_genre mg ON m.id = mg.movie_id
                                    GROUP BY m.id HAVING LOWER(title) LIKE LOWER('%?%')`;
            const str: string | undefined = req.query.string as string; // Explicitly cast to string
            // const data = await this.db.query(sql, [str]);

            const data = [
                {
                    id: 40,
                    title: "Cry, the Beloved Country",
                    description:
                        "A South-African preacher goes to search for his wayward son who has committed a crime in the big city.",
                    release_year: 1995,
                    added_at: "2024-04-26",
                    duration: 106,
                    directors: "Darrell James Roodt",
                    actors: "Richard Harris, James Earl Jones, Charles S. Dutton, Vusi Kunene, Tsholofelo Wechoemang, Dolly Rathebe, Jack Robinson, Ramalao Makhene, Jennifer Steyn, Ian Roberts, David Clatworthy, Somizi Mhlongo",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama",
                },
                {
                    id: 178,
                    title: "Love & Human Remains",
                    description:
                        "In a Canadian metropolis, failed actor David shares a place with the bookish Candy, whom he dated before coming out as gay. While David, who now waits tables, pursues an aimless romance with a younger coworker, Candy dabbles in both same-sex and heterosexual affairs. As David and Candy's odd assortment of friends — including a telepathic sex worker and an ill-tempered yuppie — pass in and out of their beds, a serial murder stalks the city's women.",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 100,
                    directors: "Denys Arcand",
                    actors: "Thomas Gibson, Ruth Marshall, Cameron Bancroft, Mia Kirshner, Joanne Vannicola, Matthew Ferguson, Rick Roberts, Aidan Devine, Robert Higden, Sylvain Morin, Ben Watt, Karen Young, Serge Houde, Polly Shannon, Annie Juneau, Alex Wylding, Maurice Podbrey, Geneviève Angers, Josée Boisvert, Aimée Castle, Rod Charlebois, Ellen David, Andy Delisle, Suzanne Desautels, Maximilian Devree, Charles S. Doucet, Nathalie Goguen, Kim Handysides, Joan Heney, Lisa Hull, Barbara Jones, Luc Leblanc, John Lozano, Gary McKeehan, Michèle-Barbara Pelletier, Maxim Roy, Harry Strandjofski",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Drama",
                },
                {
                    id: 179,
                    title: "Mad Love",
                    description:
                        "Matt falls for Casey, the new girl in school. She's fun-loving and eccentric, but there's a darkness to her whimsy that Matt can't begin to comprehend. When Casey attempts to commit suicide, her parents place her in a mental institution. Matt springs her out, and together the young lovers head on a road trip. They believe their love can cure Casey's problems. Matt starts to wonder, though, if are they inspired or misguided.",
                    release_year: 1995,
                    added_at: "2024-04-26",
                    duration: 95,
                    directors: "Antonia Bird",
                    actors: "Chris ODonnell, Drew Barrymore, Matthew Lillard, Richard Chaim, Robert Nadir, Joan Allen, Jude Ciccolella, Amy Sakasitz, T.J. Lowther, Kevin Dunn, Sharon Collar, Selene H. Vigil, Valerie M. Agnew, Roisin Dunne, Elizabeth F. Davis, Todd Sible, Leslie Do Qui, Patrick Ryals, Angela Hall, Hunt Holman, Sandra Singler, Allen Galli, Gregg Gilmore, Liev Schreiber, Angelina Torres, Stefan Enriquez, Yvonne C. Orona, Pedro García, Elaine Miles",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance",
                },
                {
                    id: 249,
                    title: "Immortal Beloved",
                    description:
                        "A chronicle of the life of infamous classical composer Ludwig van Beethoven and his painful struggle with hearing loss. Following Beethoven's death in 1827, his assistant, Schindler, searches for an elusive woman referred to in the composer's love letters as immortal beloved. As Schindler solves the mystery, a series of flashbacks reveal Beethoven's transformation from passionate young man to troubled musical genius.",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 121,
                    directors: "Bernard Rose",
                    actors: "Gary Oldman, Jeroen Krabbé, Isabella Rossellini, Johanna ter Steege, Marco Hofschneider, Miriam Margolyes, Barry Humphries, Valeria Golino, Gerard Horan, Christopher Fulford, Luigi Diberti, Michael Culkin, Sandra Voe, Bernard Rose, Alexandra Pigg, Donal Gibson, Matthew North, Geno Lechner, Claudia Solti, Rory Edwards, Hannes Flaschberger, Leo Faulkner, Fintan McKeown, Everton Nelson, Jindra Petráková, Marek Vašut, Hugo Kaminský, Stanislav Behal, Arna Mohelská, Stepan Hlatky, Gordon Lovitt, Anna Kolínská, Johan Kolinsky, Josef Kolínský, Jan Kuželka, Barbora Srncová, Bruce Davey",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Music,Romance",
                },
                {
                    id: 360,
                    title: "I Love Trouble",
                    description:
                        "Rival Chicago reporters Sabrina Peterson and Peter Brackett join forces to uncover a train wreck conspiracy.",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 123,
                    directors: "Charles Shyer",
                    actors: "Nick Nolte, Julia Roberts, Saul Rubinek, James Rebhorn, Robert Loggia, Kelly Rutherford, Olympia Dukakis, Marsha Mason, Eugene Levy, Charles Martin Smith, Dan Butler, Paul Gleason, Jane Adams, Lisa Lu, Nora Dunn, Hallie Meyers-Shyer, Boone David Cates, Richard Brown, Clark Gregg, Kevin Breznahan, Anna Holbrook, Cindy Katz, Jay Wolpert, Andy Milder, Dorothy Lyman, Dafidd McCracken, Keith Gordon, Jim Peppers, Lisa Cloud, Larry Margo, Marianne Murciano, Sally Meyers Kovler, Jody Gottlieb, Kathryn Weiss, Jonathan Kovler, Bruce A. Block, Joseph DOnofrio, Barry Sobel, Laura Mae Tate, Brian Fenwick, Frankie Faison, Mike Bacarella, James Kimo Wills, Oscar Jordan, Megan Cavanagh, Patrick St. Esprit, Michael Edgar Myers, Paul Hirsch, Jessica Lundy, Nestor Serrano, Mary Seibel, Annie Meyers-Shyer, Doug Spinuzza, Eric Poppick, Rebecca Cross, Lisa Roberts Gillan, Lucy Lin, Billie Worley, Chad Einbinder, Michael Cargile, Karl Plouffe, Matthew Lindvig, Robin Duke, Maura Russo, Blaire Baron, Michael Quill, Jeff Alpert, Lena Banks, Lou Cass, Michael George, Bob Harks, Dale Hawes, Martha Albrand, Kurt V. Hulett, Jack Rooney, John-Michael Steele",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 381,
                    title: "When a Man Loves a Woman",
                    description:
                        "An airline pilot and his wife are forced to face the consequences of her alcoholism when her addictions threaten her life and their daughter's safety. While the woman enters detox, her husband must face the truth of his enabling behavior.",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 126,
                    directors: "Luis Mandoki",
                    actors: "Andy García, Meg Ryan, Tina Majorino, Philip Seymour Hoffman, Lauren Tom, Mae Whitman, Ellen Burstyn, Eugene Roche, Gail Strickland, Steven Brill, Susanna Thompson, Erinn Canavan, LaTanya Richardson Jackson, Bari K. Willerford, James Jude Courtney, Jacques De Groot, Anne Ohliger, Tony Montero, Cynthia Mace, Jennie Yee, William Frankfather, Ellen Geer, Angelina Fiordellisi, Elizabeth Lang, Syd Field, Peer Ebbighausen, Ronald Bass, Joe Drago, Andrew Magarian, Amy Treese, Brandis Kemp, Judith Friend, Deana Kobrynski, Rico E. Anderson, Lena Banks, Richard Bradford, Al Franken, Craig Richards, Reed Rudy, Joseph Quinn Simpkins",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance",
                },
                {
                    id: 453,
                    title: "For Love or Money",
                    description:
                        "New York concierge Doug Ireland wants to go into business for himself and refurbish a hotel on Roosevelt Island, N.Y., but he needs an investor. With a few weeks left before his option on the site runs out, Doug agrees to help wealthy Christian Hanover conceal his affair with salesgirl Andy Hart from his wife. Despite his own attraction to Andy, Doug tries to stay focused on getting Christian to invest $3 million in his project.",
                    release_year: 1993,
                    added_at: "2024-04-26",
                    duration: 94,
                    directors: "Barry Sonnenfeld",
                    actors: "Michael J. Fox, Gabrielle Anwar, Anthony Higgins, Fyvush Finkel, Sandra Reaves-Phillips, LaChanze, Mike Moyer, Saverio Guerra, Daniel Hagen, Paula Laurence, Donna Mitchell, Debra Monk, Michael Tucker, Bob Balaban, Isaac Mizrahi, Dan Hedaya, Simon Jones, Udo Kier, Patrick Breen, Diane Brill, Susan Blommaert, Nicole Beach, Susan Ringo, John Cunningham, Ann McDonough, Richmond Hoxie, Alice Playten, Erick Avari, Douglas Seale, David Lipman, Le Clanché du Rand, Anne Lange, Salem Ludwig, Louis Cantarini, Hikari Takano, Jed Krascella, Gabor Morea, Beverly Peer, Rob Scott, Mark Zimmerman, Al Cerullo, Dan Brennan, Francis Dumaurier, Bobby Short, Suzanne ONeill, Tim Gallin, Steven Randazzo, Steve Ames, Harry Elgin, Alvin Alexis, Nick Cosco, Jane Deacy, Cynthia Bailey, Anna Bayle, Danya, Angelika Kallio, Kimora Lee Simmons, Melanie Landestoy, Kimberly Marler, Marpessa, Teresa Stewart, Akure Wall, Veronica Webb",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 477,
                    title: "What's Love Got to Do with It",
                    description:
                        "Singer Tina Turner rises to stardom while mustering the courage to break free from her abusive husband Ike.",
                    release_year: 1993,
                    added_at: "2024-04-26",
                    duration: 118,
                    directors: "Brian Gibson",
                    actors: "Angela Bassett, Laurence Fishburne, Vanessa Bell Calloway, Jenifer Lewis, Khandi Alexander, Richard T. Jones, RaeVen Larrymore Kelly, Chi McBride, Penny Johnson Jerald, Phyllis Yvonne Stickney, Sherman Augustus, Cora Lee Day, Virginia Capers, Barry Shabaka Henley, Bo Kane, Jackie OBrien, Michael Colyar, Rob LaBelle, Patricia Sill, Shavar Ross, Damon Hines, Suli McCullough, Daniel McDonald, ONeal Compton, Rose Jackson, Tina Turner, Gene Groove Allen, Timmy Cappello",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,History,Music",
                },
                {
                    id: 600,
                    title: "Love and a .45",
                    description:
                        "Small-time criminal Watty Watts attempts to rob a convenience store with his drug-addict buddy, Billy Mack Black. The robbery, however, leads to murder, and soon Watty leaves Billy behind and goes on the run with his beloved girlfriend, Starlene. Heading toward Mexico, the fugitive couple gets plenty of media coverage, until there are even more people on their trail. Can Watty and Starlene make it south of the border without getting caught?",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 101,
                    directors: "C.M. Talkington",
                    actors: "Gil Bellows, Renée Zellweger, Rory Cochrane, Jeffrey Combs, Jace Alexander, Peter Fonda, Ann Wedgeworth, Jack Nance, Charlotte Ross, Michael Bowen, Wiley Wiggins, Scott Roland",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Crime,Thriller",
                },
                {
                    id: 603,
                    title: "Bye Bye Love",
                    description:
                        "With varying degrees of success, recently divorced friends Dave, Vic and Donny are trying to move on with their lives. Vic feels vilified by his ex-wife's parents, while Donny has a shaky bond with his teen daughter, Emma. Dave, meanwhile, has an enviable problem -- he has more dates than he can handle. As they confront their post-marital challenges, the men take solace in one another's plights.",
                    release_year: 1995,
                    added_at: "2024-04-26",
                    duration: 106,
                    directors: "Sam Weisman",
                    actors: "Matthew Modine, Randy Quaid, Paul Reiser, Janeane Garofalo, Amy Brenneman, Eliza Dushku, Ed Flanders, Maria Pitillo, Lindsay Crouse, Ross Malinger, Johnny Whitworth, Wendell Pierce, Mae Whitman, Amber Benson, Rob Reiner, Danny Masterson, Jack Black, Cameron Boyd",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 626,
                    title: "A Thin Line Between Love and Hate",
                    description:
                        "Nightclub manager Darnell Wright is a perpetual playboy who is almost as devoted to his job as he is to the pursuit of beautiful women. After he sets his sights on the ultra-classy Brandi Web, he launches an all-out assault to win her heart. Ultimately, charm, lust and passion prevail, but Darnell learns the hard way that when you play, you pay. Brandi is much harder to get rid of than she was to get--especially when she realizes that she has a rival vying for Darnell's affection. When he finally decides to call it quits, Brandi becomes an obsessed femme fatale stalking the new love of her life.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 108,
                    directors: "Martin Lawrence",
                    actors: "Lynn Whitfield, Martin Lawrence, Regina King, Della Reese, Bobby Brown, Malinda Williams, Daryl Mitchell, Roger E. Mosley, Simbi Khali, Tangie Ambrose, Wendy Raquel Robinson, Miguel A. Núñez, Jr., Faizon Love, Michael Taliferro, Tommy Lister Jr., Tracy Morgan, Stacii Jae Johnson, Dartanyan Edmonds",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Crime,Romance,Thriller",
                },
                {
                    id: 713,
                    title: "Of Love and Shadows",
                    description:
                        "Irene is a magazine editor living under the shadow of the Pinochet dictatorship in Chile. Francisco is a handsome photographer and he comes to Irene for a job. As a sympathizer with the underground resistance movement, Francisco opens her eyes and her heart to the atrocities being committed by the state.",
                    release_year: 1994,
                    added_at: "2024-04-26",
                    duration: 103,
                    directors: "Betty Kaplan",
                    actors: "Jennifer Connelly, Antonio Banderas, Stefania Sandrelli, Diego Wallraff, Camilo Gallardo, Patricio Contreras, Jorge Rivera López, Angela Ragno, Jacques Arndt, Alejandro Toccalino, Jorge Ochoa, Mercedes Morán",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama",
                },
                {
                    id: 750,
                    title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
                    description:
                        "After the insane General Jack D. Ripper initiates a nuclear strike on the Soviet Union, a war room full of politicians, generals and a Russian diplomat all frantically try to stop the nuclear strike.",
                    release_year: 1964,
                    added_at: "2024-04-26",
                    duration: 95,
                    directors: "Stanley Kubrick",
                    actors: "Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn, Slim Pickens, Peter Bull, James Earl Jones, Tracy Reed, Jack Creley, Frank Berry, Robert ONeil, Glenn Beck, Roy Stephens, Shane Rimmer, Hal Galili, Paul Tamarin, Laurence Herder, John McCarthy, Gordon Tanner, Burnell Tucker, Victor Harrington",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,War",
                },
                {
                    id: 937,
                    title: "Love in the Afternoon",
                    description:
                        "Lovestruck conservatory student Ariane pretends to be just as much a cosmopolitan lover as the worldly mature Frank Flannagan hoping that l’amour will take hold.",
                    release_year: 1957,
                    added_at: "2024-04-26",
                    duration: 130,
                    directors: "Billy Wilder",
                    actors: "Gary Cooper, Audrey Hepburn, Maurice Chevalier, John McGiver, Van Doude, Lise Bourdin, Olga Valéry, Paul Bonifas, Audrey Long, Charles Lemontier, Eve Marley, Moustache, Jean Ozenne, Marcelle Praince, Betty Schneider, Alexandre Trauner, Audrey Young",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 1010,
                    title: "The Love Bug",
                    description:
                        "Down-on-his-luck race car driver Jim Douglas teams up with a little VW Bug that has a mind of its own, not realizing Herbie's worth until a sneaky rival plots to steal him.",
                    release_year: 1968,
                    added_at: "2024-04-26",
                    duration: 107,
                    directors: "Robert Stevenson",
                    actors: "Dean Jones, Michele Lee, David Tomlinson, Buddy Hackett, Joe Flynn, Benson Fong, Andy Granatelli, Joe E. Ross, Iris Adrian, Ned Glass, Robert Foulk, Gil Lamb, Barry Kelley, Nicole Jaffe, Gary Owens, Wally Boag, Russ Caldwell, Max Balchowsky, Peter Renaday, Brian Fong, Alan Fordney, Stan Duke, Gary Owens, Chick Hearn, Pedro Gonzalez Gonzalez, Dale Van Sickel, Regis Parton, Regina Parton, Fred Stromsoe",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Family,Fantasy",
                },
                {
                    id: 1045,
                    title: "Love Is All There Is",
                    description:
                        "The Malacicis, a hard-working Italian family recently immigrated from Florence, open a fancy restaurant in the Bronx, N.Y., drawing the ire of another clan. Mike and Sadie Capomezzo, equally hard-working Sicilian caterers from the area, find they cannot stand Piero and Maria Malacici. But things get complicated when the Malacicis' daughter, Gina, and the Capomezzos' son, Rosario, fall in love.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 105,
                    directors: "Joseph Bologna, Renée Taylor",
                    actors: "Lainie Kazan, Paul Sorvino, Barbara Carrera, Joseph Bologna, Angelina Jolie, Nathaniel Marston, Renée Taylor, William Hickey, Dick Van Patten, Abe Vigoda, Connie Stevens, Joy Behar, Irma St. Paule, Andrea Shreeman, Annie Meisels, Alanna Ubach, Celeste Russi, Gabriel Bologna, Edith Fields, Ronald Maccone, Emanuele Secci",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 1057,
                    title: "Everyone Says I Love You",
                    description:
                        "A New York girl sets her father up with a beautiful woman in a shaky marriage while her half sister gets engaged.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 101,
                    directors: "Woody Allen",
                    actors: "Drew Barrymore, Edward Norton, Alan Alda, Julia Roberts, Woody Allen, Lukas Haas, Goldie Hawn, Gaby Hoffmann, Natalie Portman, Tim Roth, David Ogden Stiers, Natasha Lyonne, Billy Crudup, Robert Knepper, Diva Gray, Patrick Cranshaw, Kevin Hagan, Itzhak Perlman, Trude Klein, Isiah Whitlock Jr., Edward Hibbert, Colleen Dunn, Susan Misner, Frederick Rolf, Timothy Jerome, Daisy Prince, Ruth Gottschall, Monica McSwain, Jill Nicklaus, Myra Lucretia Taylor, Paolo Seganti, Robert Khakh, Scotty Bloch, Valda Setterfield, Tony Sirico, Ray Garvey, Christy Carlson Romano, Gabriel Millman, Ed Hodson, Darren Lee, Cynthia Onrubia, Nancy Ticotin, Emily Bindiger, Michael Mark, Ami Almendral, Madeline Balmaceda, Vivian Cherry, Tommie Baxter, Jeff DeRocker, Cherylyn Jones, Tina Paul, Vikki Schnurr, Navah Perlman, Barbara Hollander, John Griffin, Waltrudis Buck, Kevin Bogue, Pamela Everett, Gregory Mitchell, Dana Moore, Troy Myers, Joe Orrach, Michael OSteen, Luis Martin Perez, Krissy Richmond, Linda Kuriloff, Helen Miles, Arlene Martin, Rene Ceballos, Colton Green, Lisa LeGuillou, Joe Locarro, Andrew Pacho, John Selya, Jo Telford, Andrea Piedimonte, Gerry Burkhardt, Eileen Casey, Shelley Frankel, Fred Mann III, Kathy Sanson, Frank Pietri, Robert Walker, Devalle Hayes, Damon McCloud, Tommy John, Lindsy Canuel, Richard Cummings, Kristen Pettet, Patrick Lavery, Jonathan Giordano, Michel Moinot, Don Correia, Sean Grant, Roland Hayes, Delphine T. Mantz, Joanne McHugh, John Mineo, Willie Rosario, Jerome Vivona, Cindy Cobitt, Al Dana, Kevin De Simone, Paul Evans, Chrissy Faith, Jeff Lyons, Jenna Miles, Robert Ragaini, Lenny Roberts, Annette Sanders, Terry Textor, Vanéese Y. Thomas, Ashley H. Wilkinson, Chris Cardona, Olivia Hayman, Lisa Cangelosi, Malinda Farrington",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 1173,
                    title: "The Cook, the Thief, His Wife & Her Lover",
                    description:
                        "The wife of an abusive criminal finds solace in the arms of a kind regular guest in her husband's restaurant.",
                    release_year: 1989,
                    added_at: "2024-04-26",
                    duration: 124,
                    directors: "Peter Greenaway",
                    actors: "Richard Bohringer, Michael Gambon, Helen Mirren, Alan Howard, Tim Roth, Ciarán Hinds, Liz Smith, Gary Olsen, Ewan Stewart, Roger Ashton-Griffiths, Ian Dury, Diane Langton, Prudence Oliver, Ron Cook, Emer Gillespie, Janet Henfrey, Willie Ross, Roger Lloyd Pack, Alex Kingston, Bob Goody, Paul Russell, Arnie Breeveld, Tony Alleff, Ian Sears, Peter Rush, Pauline Mayer, Ben Stoneham, Andy Wilson, John Mullis, Flavia Brilli, Sophie Goodchild, Alex Fraser, Michael Clark, Gary Logan, Tim Geary, Saffron Rainey, Hywel Williams-Ellis, Michael Maguire, Patric Walters, Sue Maund, Nick Brozovic, Caroline Pagano, Keith Barrows, Yolande Brener, Irene Palko, Brenda Edwards",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Crime,Drama",
                },
                {
                    id: 1398,
                    title: "In Love and War",
                    description:
                        "After teenage ambulance driver Ernest Hemingway takes shrapnel in the leg during World War I, he falls in love with Agnes von Kurowsky, a beautiful older nurse at the hospital where he's sent to recover. Their affair slowly blossoms, until Hemingway boldly asks Agnes to be his wife and journey to America with him.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 113,
                    directors: "Richard Attenborough",
                    actors: "Sandra Bullock, Chris ODonnell, Mackenzie Astin, Margot Steinberg, Alan Bennett, Ingrid Lacey, George Rossi, Carlo Croccolo, Laura Nardi, Tara Hugo, Diane Witter, Allegra Di Carpegna, Mindy Lee Raskin, Tracy Hostmyer, Kaethe Cherney, Lauren Booth, Rebecca Craig, Frances Riddelle, Wendi Peters, Maria Petrucci, Valeria Fabbri, Ian Kelly, Colin Stinton, Vincenzo Nicoli, Raffaello Degruttola, Todd Curran, Emilio Bonucci, Matthew Sharp, Nick Brooks, Tom Goodman-Hill, Doreen Mantle, Vincent Riotta, Joseph Long, Kay Hawtrey, Noah Reid, Laura Martelli, Philippe Leroy, Richard Fitzpatrick, Terence Sach, Gigi Vivan, Giuseppe Bonato",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance",
                },
                {
                    id: 1436,
                    title: "Falling in Love Again",
                    description:
                        "Harry and Sue Lewis met in the 40s as teenagers living in the Bronx. He was an aspiring architect, she was the most beautiful girl in school, and both had a fondness for bran muffins. They fell in love, got married, moved to Los Angeles, and had two kids. While struggling with his midlife crisis, Harry receives an invitation for his high school's reunion back so he takes Sue and their teenage kids on a cross-country car trip back to the Big Apple. Will they see in the Bronx what they expected? Will the good memories from their past help rekindle their fading love? Is it too late to dream?",
                    release_year: 1980,
                    added_at: "2024-04-26",
                    duration: 103,
                    directors: "Steven Paul",
                    actors: "Elliott Gould, Susannah York, Kaye Ballard, Stuart Paul, Michelle Pfeiffer, Robert Hackman, Herbert Rudley, Marian McCargo, Steven Paul, Tallie Cochrane, Patrick Wright, Bonnie Paul, Tony ODell, Ben Frank, John Diehl",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance",
                },
                {
                    id: 1475,
                    title: "Kama Sutra: A Tale of Love",
                    description:
                        "Tara and Maya are two inseparable friends in India. Their tastes, habits, and hobbies are the same. Years later, the two have matured, but have maintained their friendship. Tara gets married to the local prince, Raj Singh, who soon succeeds the throne as the sole heir. After the marriage, Raj gets bored of Tara and starts seeking another female to satisfy his sexual needs. He notices Maya and is instantly attracted to her. He has her included as one of his courtesans, and is intimate with her. Watch what happens when Tara finds out and the extent she will go to keep her marriage intact.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 117,
                    directors: "Mira Nair",
                    actors: "Indira Varma, Sarita Choudhury, Ramon Tikaram, Naveen Andrews, Rekha, Khalid Tyabji, Arundathi Nag, Surabhi Bhansali, Garima Dhup, Pearl Padamsee, Kusum Haidar, Harish Patel, Ranjit Chowdhry, Achala Sachdev, Arjun Sajnani, Avijit Dutt, Anjum Rajabali, Siddharth Anand Kumar, Debi Basu, Rahul Vohra, Manize Boga, Prabeen Singh, Cinia Jain, Urvashi Nair, Bhanumathi Rao, Vasudeo Bhatt, Moneeka Misra Tanvir, Mina Sareen, Maya Krishna Rao, Shyamoli Varma, Nandita Mehrotra, Zoya Akhtar, Deepti Datt, Piu Dutt, Dinaz Stafford, Purnima Raju, Daphnée Breytenbach, Celesteann Cruz, Nizami Chattarpur, Yasmine Stafford, Sunil Chabra, Himanshu Malik, Shubha Mudgal",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,History,Romance",
                },
                {
                    id: 1477,
                    title: "Love Jones",
                    description:
                        "Darius Lovehall is a young black poet in Chicago who starts dating Nina Moseley, a beautiful and talented photographer. While trying to figure out if they've got a love thing or are just kicking it, they hang out with their friends, talking about love and sex. Then Nina tests the strength of Darius' feelings and sets a chain of romantic complications into motion.",
                    release_year: 1997,
                    added_at: "2024-04-26",
                    duration: 108,
                    directors: "Theodore Witcher",
                    actors: "Larenz Tate, Nia Long, Isaiah Washington, Bill Bellamy, Lisa Nicole Carson, Marie-Françoise Theodore, Khalil Kain, Leonard Roberts, Bernadette Speakes",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Drama,Romance",
                },
                {
                    id: 1541,
                    title: "Addicted to Love",
                    description:
                        "Good-natured astronomer Sam is devastated when the love of his life leaves him for a suave Frenchman. He therefore does what every other normal dumpee would do — go to New York and set up home in the abandoned building opposite his ex-girlfriend's apartment, wait until she decides to leave her current lover, and then win her back.",
                    release_year: 1997,
                    added_at: "2024-04-26",
                    duration: 100,
                    directors: "Griffin Dunne",
                    actors: "Meg Ryan, Matthew Broderick, Kelly Preston, Tchéky Karyo, Maureen Stapleton, Nesbitt Blaisdell, Remak Ramsay, Lee Wilkof, Dominick Dunne, Susan Forristal, Larry Pine, Debbon Ayer, Maurizio Benazzo, Paolo Calamari, Helmar Augustus Cooper, Tom Forrest, Shoshanna Gleich, Jacqueline Heinze, Mike Hodge, Daniel Dae Kim, Bill Kux, Steve McAuliff, Conrad McLaren, Bill Timoney, David Boston, Bob Bowersox, Jordan Nia Elizabeth, Martin Pfefferkorn",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Romance",
                },
                {
                    id: 1600,
                    title: "She's So Lovely",
                    description:
                        "After being released from a psychiatric institution, a man tries to redeem himself in the eyes of his now-ex wife from the events that led up to his incarceration.",
                    release_year: 1997,
                    added_at: "2024-04-26",
                    duration: 100,
                    directors: "Nick Cassavetes",
                    actors: "Sean Penn, Robin Wright, John Travolta, Harry Dean Stanton, Debi Mazar, James Gandolfini, David Thornton, Susan Traylor, Bobby Cooper, John Marshall Jones, Kelsey Mulrooney, Chloe Webb, James Soravilla, Jamie Bozian, Paul Johansson, Justina Machado, Tito Larriva, Ilya Brodsky, Burt Young, Chris Kinkade, Gena Rowlands, Neill Barry, Clayton Landey, Jason OMalley, Dennis Fanning, John Cundari, Noon Orsatti, Nina Barry, Kristina Malota, Nicolette Little, Lester Mathews, Talia Shire, David Sherrill",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance,Thriller",
                },
                {
                    id: 1685,
                    title: "I Love You, I Love You Not",
                    description:
                        "School student and her European-born grandmother share sad stories of their lives.",
                    release_year: 1996,
                    added_at: "2024-04-26",
                    duration: 88,
                    directors: "Billy Hopkins",
                    actors: "Claire Danes, Jude Law, Jeanne Moreau, James Van Der Beek, Kris Park, Lauren Fox, Emily Burkes-Nossiter, Carrie Szlasa, Natasha Wolff, Josiah A. Mayo, Brandon Danziger, Alex Ballar, Elżbieta Czyżewska, Frederick Neumann, Peter F. Hopkins, Jerry Tanklow, Julia Stiles, Ashley Fletcher, Brittany Fletcher, Robert Sean Leonard, Hélène Cardona, Bethany Joy Lenz",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Family,Romance",
                },
                {
                    id: 1851,
                    title: "Leather Jacket Love Story",
                    description:
                        "Kyle is 18, an aspiring poet hoping to find inspiration by moving to the arty Silver Lake neighborhood of LA, and maybe love too. On day one, he finds a funky coffee shop, where he hopes to do some writing, but instead meets an older hunk.",
                    release_year: 1998,
                    added_at: "2024-04-26",
                    duration: 85,
                    directors: "David DeCoteau",
                    actors: "Sean Tataryn, Christopher Bradley, Geoff Moody, Héctor Mercado, Stephen J. McCarthy, Erin Krystle, Craig Olsen, Mink Stole, Nicholas Worth, William Butler, Worthie Meacham, Arlene Golonka, Dennis Larkin, Sophie Poster, Daniel Escobar, Bob Prest, Morris Kight, Steve Mateo, David Wolfson, Moist Towelette",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,Drama,Romance",
                },
                {
                    id: 1852,
                    title: "Love Walked In",
                    description:
                        "Two romantically involved down-and-out lounge singers get involved in a caper.",
                    release_year: 1997,
                    added_at: "2024-04-26",
                    duration: 95,
                    directors: "Juan José Campanella",
                    actors: "Denis Leary, Terence Stamp, Aitana Sánchez-Gijón, Michael Badalucco, Danny Nucci, Gene Canfield, Marj Dusay, Neal Huff, J.K. Simmons, Justin Lazard, Rocco Sisto, Jimmy McQuaid, Murphy Guyer, Paul Eagle, Fiddle Viracola, Jeremy Webb, Gregory Scanlon, Gary DeWitt Marshall, D.C. Benny, Moira Kelly, Patrick Boll",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Thriller",
                },
                {
                    id: 2190,
                    title: "Why Do Fools Fall In Love",
                    description:
                        "In the mid-80s, three women (each with an attorney) arrive at the office of New York entertainment manager, Morris Levy. One is an L.A. singer, formerly of the Platters; one is a petty thief from Philly; one teaches school in a small Georgia town. Each claims to be the widow of long-dead doo-wop singer-songwriter Frankie Lyman, and each wants years of royalties due to his estate, money Levy has never shared. During an ensuing civil trial, flashbacks tell the story of each one's life with Lyman, a boyish, high-pitched, dynamic performer, lost to heroin. Slowly, the three wives establish their own bond.",
                    release_year: 1998,
                    added_at: "2024-04-26",
                    duration: 116,
                    directors: "Gregory Nava",
                    actors: "Larenz Tate, Halle Berry, Vivica A. Fox, Lela Rochon, Pamela Reed, Clifton Powell, Paul Mazursky, Miguel A. Núñez Jr., James Gleason, Ben Vereen, Paula Jai Parker, Little Richard, Miya McGhee, Aries Spears, Alexis Cruz, David Barry Gray, Marcello Thedford, Jon Huertas, Craig Kirkwood, Lucille M. Oliver, Alex Thomas",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Romance",
                },
                {
                    id: 2255,
                    title: "Young Doctors in Love",
                    description:
                        "An 'Airplane!'-style spoof of hospital soap operas—a brilliant young trainee can't stand the sight of blood; a doctor romances the head nurse in order to get the key to the drugs cabinet; and there's a mafioso on the loose disguised as a woman.",
                    release_year: 1982,
                    added_at: "2024-04-26",
                    duration: 96,
                    directors: "Garry Marshall",
                    actors: "Sean Young, Michael McKean, Gary Friedkin, Kyle T. Heffner, Rick Overton, Crystal Bernard, Ted McGinley, Saul Rubinek, Harry Dean Stanton, Patrick Macnee, Dabney Coleman, Hector Elizondo, Peggy Trentini, Pamela Reed, Taylor Negron, Patrick Collins, Michael Richards, Titos Vandis, Richard Dean Anderson, Monique Gabrielle, Haunani Minn, Becky Gonzalez, Lynne Marie Stewart, Toni Hudson, Frank Pesce, Nicholas Mele, Michael Damian, Steven Ford, Stuart Damon, Jaime Lyn Bauer, Tom Ligon, Kin Shriner, Janine Turner, Jacklyn Zeman, Diane Markoff, Walter Scott, Reynaldo Rey, Billie Bird, Millee Taggart, Larry Jenkins, Stuart Charno, John Steadman, Scott Marshall, George Furth, Ed Begley Jr., Michael Elias, Kimberly McArthur, Rose Michtom, Paul Stanley, Cynthia Geary, Susan Lucci, John E. Coleman, Demi Moore",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy",
                },
                {
                    id: 2314,
                    title: "Beloved",
                    description:
                        "After Paul D. finds his old slave friend Sethe in Ohio and moves in with her and her daughter Denver, a strange girl comes along by the name of Beloved. Sethe and Denver take her in and then strange things start to happen...",
                    release_year: 1998,
                    added_at: "2024-04-26",
                    duration: 172,
                    directors: "Jonathan Demme",
                    actors: "Oprah Winfrey, Danny Glover, Thandiwe Newton, Kimberly Elise, LisaGay Hamilton, Albert Hall, Irma P. Hall, Beah Richards, Vertamae Grosvenor, Dorothy Love Coates, Thelma Houston, Charles Napier, Jason Robards, Joey Perillo, Hill Harper, Brian Hooks, Dashiell Eaves, Jude Ciccolella, Wes Bentley, Frederick Strother, Harry Northup, Anthony Chisholm, Joe Toutebon, Tracey Walter, Paul Lazar, Robert W. Castle, Jane White, Pauletta Washington, Karen Vicks, Harold Gould",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Drama,Horror,Thriller",
                },
                {
                    id: 2396,
                    title: "Shakespeare in Love",
                    description:
                        "Young Shakespeare is forced to stage his latest comedy, Romeo and Ethel, the Pirate's Daughter, before it's even written. When a lovely noblewoman auditions for a role, they fall into forbidden love -- and his play finds a new life (and title). As their relationship progresses, Shakespeare's comedy soon transforms into tragedy.",
                    release_year: 1998,
                    added_at: "2024-04-26",
                    duration: 123,
                    directors: "John Madden",
                    actors: "Joseph Fiennes, Gwyneth Paltrow, Geoffrey Rush, Tom Wilkinson, Judi Dench, Imelda Staunton, Colin Firth, Ben Affleck, Simon Callow, Steven Beard, Jim Carter, Rupert Everett, Martin Clunes, Tim McMullan, Joe Roberts, Antony Sher, Georgie Glen, Nicholas Boulton, Barnaby Kay, Mark Williams, Jill Baker, Nicholas Le Prevost, Rebecca Charles, Bob Barrett, Simon Day, Bridget McConnell, Sandra Reinton, Jason Round, Rupert Farley, Adam Barker, Harry Gostelow, Alan Cody, David Curtiz, Gregor Truter, Amber Glossop, Robin Davies, Hywel Simons, Roger Morlidge, Daniel Brocklebank, Mark Saban, Timothy Kightley, Roger Frost, Rachel Clarke, Lucy Speed, John Ramm, Paul Bigley, Patrick Barlow, Steven ODonnell, John Inman",
                    cover_img_url: null,
                    trailer_url: null,
                    film_url: null,
                    genres: "Comedy,History,Romance",
                },
            ];

            res.status(200).json(data);
        } catch (err) {
            res.status(500).json({ err });
        }
    };
}

export default SearchController;
